# Generated by Django 2.0 on 2019-04-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=255)),
                ('cbrand', models.CharField(max_length=255)),
                ('cseries', models.CharField(max_length=255)),
                ('ccore_num', models.CharField(max_length=255)),
                ('cmodel', models.CharField(max_length=255)),
                ('cprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=255)),
                ('gbrand', models.CharField(max_length=255)),
                ('gmodel', models.CharField(max_length=255)),
                ('gcolor', models.CharField(max_length=255)),
                ('gcache', models.CharField(max_length=255)),
                ('ginterface', models.CharField(max_length=255)),
                ('gtype', models.CharField(max_length=255)),
                ('gsize', models.CharField(max_length=255)),
                ('gprice', models.IntegerField()),
            ],
        ),
    ]
