# Generated by Django 2.0 on 2019-04-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zjyj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cimage',
            field=models.URLField(default='F:\\database_image\\zjyj_cpu\x08\x081.jpg', verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gq',
            name='gimage',
            field=models.ImageField(default='F:\\database_image\\zjyj_gq\x07\x081.jpg', upload_to='', verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cbrand',
            field=models.CharField(max_length=255, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='ccore_num',
            field=models.CharField(max_length=255, verbose_name='核数'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cmodel',
            field=models.CharField(max_length=255, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cname',
            field=models.CharField(max_length=255, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cprice',
            field=models.IntegerField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cseries',
            field=models.CharField(max_length=255, verbose_name='系列'),
        ),
        migrations.AlterField(
            model_name='gq',
            name='gbrand',
            field=models.CharField(max_length=255, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='gq',
            name='gcache',
            field=models.CharField(max_length=255, verbose_name='缓存'),
        ),
        migrations.AlterField(
            model_name='gq',
            name='gcolor',
            field=models.CharField(max_length=255, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='gq',
            name='ginterface',
            field=models.CharField(max_length=255, verbose_name='接口'),
        ),
        migrations.AlterField(
            model_name='gq',
            name='gmodel',
            field=models.CharField(max_length=255, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='gq',
            name='gname',
            field=models.CharField(max_length=255, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='gq',
            name='gprice',
            field=models.IntegerField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='gq',
            name='gsize',
            field=models.CharField(max_length=255, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='gq',
            name='gtype',
            field=models.CharField(max_length=255, verbose_name='类型'),
        ),
    ]
