# Generated by Django 2.2 on 2019-04-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zjyj', '0002_auto_20190416_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='cimage',
        ),
        migrations.RemoveField(
            model_name='gq',
            name='gimage',
        ),
    ]
